ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(15, 4) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS cancellation_reason TEXT,
  ADD COLUMN IF NOT EXISTS status_changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
